name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-20.04 # required for when we want to build snaps
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      # -
      #   name: Set up Snapcraft
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
      #     mkdir -p $HOME/.cache/snapcraft/download
      #     mkdir -p $HOME/.cache/snapcraft/stage-packages
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          #   SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}